### ISSUE TITLE
Sound Buttons

### ISSUE THREAD

**Issue by marcus-universe** [marcus-universe/SoundNinja#16]
# Sound Buttons improvements

> Enhancements

- [ ] Filter MP3, WAV und OGG #13 
- [x] Tags for Audiofiles #13 
- [x] Selectable Image/Icons for Buttons (Giphy implementation) #14 
- [ ] Drag and Drop Soundfiles
- [x] Add Sounds to multiple Tabs (right-click menu)
- [x] Delete Buttons (right-click menu)
- [x] Rename Buttons (right-click menu)
- [x] Adding entire Folders with Sounds

> Error Checking
- [ ] Check for duplicated paths
- [x] Check Audiofile Paths valid
- [x] Check Filetype is valid
